/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SetlistId = IDL.Text;
export const SongId = IDL.Text;
export const Setlist = IDL.Record({
  'id' : SetlistId,
  'name' : IDL.Text,
  'songIds' : IDL.Vec(SongId),
});
export const Song = IDL.Record({
  'id' : SongId,
  'bpm' : IDL.Nat,
  'key' : IDL.Text,
  'title' : IDL.Text,
  'createdBy' : IDL.Principal,
  'chordSheet' : IDL.Text,
});
export const ActiveSession = IDL.Record({
  'transposeSteps' : IDL.Int,
  'chordMode' : IDL.Text,
  'activeSetlistId' : IDL.Opt(SetlistId),
  'lastUpdated' : IDL.Int,
  'activeSongId' : IDL.Opt(SongId),
  'capoFret' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const MessageId = IDL.Nat;
export const Message = IDL.Record({
  'id' : MessageId,
  'text' : IDL.Text,
  'authorName' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateSetlist' : IDL.Func([Setlist], [], []),
  'createOrUpdateSong' : IDL.Func([Song], [], []),
  'deleteSetlist' : IDL.Func([SetlistId], [], []),
  'deleteSong' : IDL.Func([SongId], [], []),
  'getActiveSession' : IDL.Func([], [ActiveSession], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSetlist' : IDL.Func([SetlistId], [Setlist], ['query']),
  'getSong' : IDL.Func([SongId], [Song], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMessagesSince' : IDL.Func([IDL.Int], [IDL.Vec(Message)], ['query']),
  'listRecentMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'listSetlists' : IDL.Func([], [IDL.Vec(Setlist)], ['query']),
  'listSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
  'postMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchSongs' : IDL.Func([IDL.Text], [IDL.Vec(Song)], ['query']),
  'updateActiveSession' : IDL.Func([ActiveSession], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SetlistId = IDL.Text;
  const SongId = IDL.Text;
  const Setlist = IDL.Record({
    'id' : SetlistId,
    'name' : IDL.Text,
    'songIds' : IDL.Vec(SongId),
  });
  const Song = IDL.Record({
    'id' : SongId,
    'bpm' : IDL.Nat,
    'key' : IDL.Text,
    'title' : IDL.Text,
    'createdBy' : IDL.Principal,
    'chordSheet' : IDL.Text,
  });
  const ActiveSession = IDL.Record({
    'transposeSteps' : IDL.Int,
    'chordMode' : IDL.Text,
    'activeSetlistId' : IDL.Opt(SetlistId),
    'lastUpdated' : IDL.Int,
    'activeSongId' : IDL.Opt(SongId),
    'capoFret' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const MessageId = IDL.Nat;
  const Message = IDL.Record({
    'id' : MessageId,
    'text' : IDL.Text,
    'authorName' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateSetlist' : IDL.Func([Setlist], [], []),
    'createOrUpdateSong' : IDL.Func([Song], [], []),
    'deleteSetlist' : IDL.Func([SetlistId], [], []),
    'deleteSong' : IDL.Func([SongId], [], []),
    'getActiveSession' : IDL.Func([], [ActiveSession], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSetlist' : IDL.Func([SetlistId], [Setlist], ['query']),
    'getSong' : IDL.Func([SongId], [Song], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMessagesSince' : IDL.Func([IDL.Int], [IDL.Vec(Message)], ['query']),
    'listRecentMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'listSetlists' : IDL.Func([], [IDL.Vec(Setlist)], ['query']),
    'listSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
    'postMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchSongs' : IDL.Func([IDL.Text], [IDL.Vec(Song)], ['query']),
    'updateActiveSession' : IDL.Func([ActiveSession], [], []),
  });
};

export const init = ({ IDL }) => { return []; };