/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActiveSession {
  'transposeSteps' : bigint,
  'chordMode' : string,
  'activeSetlistId' : [] | [SetlistId],
  'lastUpdated' : bigint,
  'activeSongId' : [] | [SongId],
  'capoFret' : bigint,
}
export interface Message {
  'id' : MessageId,
  'text' : string,
  'authorName' : string,
  'timestamp' : bigint,
}
export type MessageId = bigint;
export type RequestStatus = { 'pending' : null } |
  { 'denied' : null } |
  { 'approved' : null };
export interface Setlist {
  'id' : SetlistId,
  'name' : string,
  'songIds' : Array<SongId>,
}
export type SetlistId = string;
export interface Song {
  'id' : SongId,
  'bpm' : bigint,
  'key' : string,
  'title' : string,
  'createdBy' : Principal,
  'chordSheet' : string,
}
export type SongId = string;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorshipLeaderRequest {
  'status' : RequestStatus,
  'requester' : Principal,
  'requestedAt' : bigint,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveWorshipLeader' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignWorshipLeader' : ActorMethod<[Principal], undefined>,
  'createOrUpdateSetlist' : ActorMethod<[Setlist], undefined>,
  'createOrUpdateSong' : ActorMethod<[Song], undefined>,
  'deleteSetlist' : ActorMethod<[SetlistId], undefined>,
  'deleteSong' : ActorMethod<[SongId], undefined>,
  'denyWorshipLeader' : ActorMethod<[Principal], undefined>,
  'fetchSongUrl' : ActorMethod<[string], string>,
  'getActiveSession' : ActorMethod<[], ActiveSession>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyWorshipLeaderRequestStatus' : ActorMethod<[], [] | [RequestStatus]>,
  'getSetlist' : ActorMethod<[SetlistId], Setlist>,
  'getSong' : ActorMethod<[SongId], Song>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorshipLeaderSession' : ActorMethod<[Principal], ActiveSession>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerWorshipLeader' : ActorMethod<[], boolean>,
  'listMessagesSince' : ActorMethod<[bigint], Array<Message>>,
  'listPendingWorshipLeaderRequests' : ActorMethod<
    [],
    Array<WorshipLeaderRequest>
  >,
  'listRecentMessages' : ActorMethod<[], Array<Message>>,
  'listSetlists' : ActorMethod<[], Array<Setlist>>,
  'listSongs' : ActorMethod<[], Array<Song>>,
  'listWorshipLeaders' : ActorMethod<[], Array<Principal>>,
  'postMessage' : ActorMethod<[string, string], undefined>,
  'releaseWorshipLeader' : ActorMethod<[], undefined>,
  'removeWorshipLeader' : ActorMethod<[Principal], undefined>,
  'requestWorshipLeader' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchSongs' : ActorMethod<[string], Array<Song>>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateActiveSession' : ActorMethod<[ActiveSession], undefined>,
  'updateMyWorshipLeaderSession' : ActorMethod<[ActiveSession], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];