/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type SongId = string;
export type SetlistId = string;
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface http_header {
    value: string;
    name: string;
}
export type MessageId = bigint;
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Song {
    id: SongId;
    bpm: bigint;
    key: string;
    title: string;
    createdBy: Principal;
    chordSheet: string;
}
export interface Setlist {
    id: SetlistId;
    name: string;
    songIds: Array<SongId>;
}
export interface Message {
    id: MessageId;
    text: string;
    authorName: string;
    timestamp: bigint;
}
export interface ActiveSession {
    transposeSteps: bigint;
    chordMode: string;
    activeSetlistId?: SetlistId;
    lastUpdated: bigint;
    activeSongId?: SongId;
    capoFret: bigint;
}
export interface WorshipLeaderRequest {
    status: RequestStatus;
    requester: Principal;
    requestedAt: bigint;
}
export interface UserProfile {
    name: string;
}
export enum RequestStatus {
    pending = "pending",
    denied = "denied",
    approved = "approved"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    approveWorshipLeader(user: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignWorshipLeader(user: Principal): Promise<void>;
    createOrUpdateSetlist(setlist: Setlist): Promise<void>;
    createOrUpdateSong(inputSong: Song): Promise<void>;
    deleteSetlist(id: SetlistId): Promise<void>;
    deleteSong(id: SongId): Promise<void>;
    denyWorshipLeader(user: Principal): Promise<void>;
    fetchSongUrl(url: string): Promise<string>;
    getActiveSession(): Promise<ActiveSession>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMyWorshipLeaderRequestStatus(): Promise<RequestStatus | null>;
    getSetlist(id: SetlistId): Promise<Setlist>;
    getSong(id: SongId): Promise<Song>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWorshipLeaderSession(leader: Principal): Promise<ActiveSession>;
    isCallerAdmin(): Promise<boolean>;
    isCallerWorshipLeader(): Promise<boolean>;
    listMessagesSince(timestamp: bigint): Promise<Array<Message>>;
    listPendingWorshipLeaderRequests(): Promise<Array<WorshipLeaderRequest>>;
    listRecentMessages(): Promise<Array<Message>>;
    listSetlists(): Promise<Array<Setlist>>;
    listSongs(): Promise<Array<Song>>;
    listWorshipLeaders(): Promise<Array<Principal>>;
    postMessage(authorName: string, text: string): Promise<void>;
    releaseWorshipLeader(): Promise<void>;
    removeWorshipLeader(user: Principal): Promise<void>;
    requestWorshipLeader(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchSongs(searchTerm: string): Promise<Array<Song>>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateActiveSession(newSession: ActiveSession): Promise<void>;
    updateMyWorshipLeaderSession(session: ActiveSession): Promise<void>;
}
import type { ActiveSession as _ActiveSession, RequestStatus as _RequestStatus, SetlistId as _SetlistId, SongId as _SongId, UserProfile as _UserProfile, UserRole as _UserRole, WorshipLeaderRequest as _WorshipLeaderRequest } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async approveWorshipLeader(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveWorshipLeader(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveWorshipLeader(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignWorshipLeader(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignWorshipLeader(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignWorshipLeader(arg0);
            return result;
        }
    }
    async createOrUpdateSetlist(arg0: Setlist): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateSetlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateSetlist(arg0);
            return result;
        }
    }
    async createOrUpdateSong(arg0: Song): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateSong(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateSong(arg0);
            return result;
        }
    }
    async deleteSetlist(arg0: SetlistId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSetlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSetlist(arg0);
            return result;
        }
    }
    async deleteSong(arg0: SongId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSong(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSong(arg0);
            return result;
        }
    }
    async denyWorshipLeader(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.denyWorshipLeader(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.denyWorshipLeader(arg0);
            return result;
        }
    }
    async fetchSongUrl(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchSongUrl(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchSongUrl(arg0);
            return result;
        }
    }
    async getActiveSession(): Promise<ActiveSession> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveSession();
                return from_candid_ActiveSession_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveSession();
            return from_candid_ActiveSession_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyWorshipLeaderRequestStatus(): Promise<RequestStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyWorshipLeaderRequestStatus();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyWorshipLeaderRequestStatus();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSetlist(arg0: SetlistId): Promise<Setlist> {
        if (this.processError) {
            try {
                const result = await this.actor.getSetlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSetlist(arg0);
            return result;
        }
    }
    async getSong(arg0: SongId): Promise<Song> {
        if (this.processError) {
            try {
                const result = await this.actor.getSong(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSong(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorshipLeaderSession(arg0: Principal): Promise<ActiveSession> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorshipLeaderSession(arg0);
                return from_candid_ActiveSession_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorshipLeaderSession(arg0);
            return from_candid_ActiveSession_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerWorshipLeader(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerWorshipLeader();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerWorshipLeader();
            return result;
        }
    }
    async listMessagesSince(arg0: bigint): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMessagesSince(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMessagesSince(arg0);
            return result;
        }
    }
    async listPendingWorshipLeaderRequests(): Promise<Array<WorshipLeaderRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPendingWorshipLeaderRequests();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPendingWorshipLeaderRequests();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async listRecentMessages(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRecentMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRecentMessages();
            return result;
        }
    }
    async listSetlists(): Promise<Array<Setlist>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSetlists();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSetlists();
            return result;
        }
    }
    async listSongs(): Promise<Array<Song>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSongs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSongs();
            return result;
        }
    }
    async listWorshipLeaders(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.listWorshipLeaders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listWorshipLeaders();
            return result;
        }
    }
    async postMessage(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.postMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postMessage(arg0, arg1);
            return result;
        }
    }
    async releaseWorshipLeader(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.releaseWorshipLeader();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.releaseWorshipLeader();
            return result;
        }
    }
    async removeWorshipLeader(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeWorshipLeader(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeWorshipLeader(arg0);
            return result;
        }
    }
    async requestWorshipLeader(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestWorshipLeader();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestWorshipLeader();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchSongs(arg0: string): Promise<Array<Song>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchSongs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchSongs(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateActiveSession(arg0: ActiveSession): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateActiveSession(to_candid_ActiveSession_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateActiveSession(to_candid_ActiveSession_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateMyWorshipLeaderSession(arg0: ActiveSession): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyWorshipLeaderSession(to_candid_ActiveSession_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyWorshipLeaderSession(to_candid_ActiveSession_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_ActiveSession_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActiveSession): ActiveSession {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_RequestStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RequestStatus): RequestStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_WorshipLeaderRequest_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorshipLeaderRequest): WorshipLeaderRequest {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RequestStatus]): RequestStatus | null {
    return value.length === 0 ? null : from_candid_RequestStatus_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SetlistId]): SetlistId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SongId]): SongId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _RequestStatus;
    requester: Principal;
    requestedAt: bigint;
}): {
    status: RequestStatus;
    requester: Principal;
    requestedAt: bigint;
} {
    return {
        status: from_candid_RequestStatus_n11(_uploadFile, _downloadFile, value.status),
        requester: value.requester,
        requestedAt: value.requestedAt
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    transposeSteps: bigint;
    chordMode: string;
    activeSetlistId: [] | [_SetlistId];
    lastUpdated: bigint;
    activeSongId: [] | [_SongId];
    capoFret: bigint;
}): {
    transposeSteps: bigint;
    chordMode: string;
    activeSetlistId?: SetlistId;
    lastUpdated: bigint;
    activeSongId?: SongId;
    capoFret: bigint;
} {
    return {
        transposeSteps: value.transposeSteps,
        chordMode: value.chordMode,
        activeSetlistId: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.activeSetlistId)),
        lastUpdated: value.lastUpdated,
        activeSongId: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.activeSongId)),
        capoFret: value.capoFret
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    denied: null;
} | {
    approved: null;
}): RequestStatus {
    return "pending" in value ? RequestStatus.pending : "denied" in value ? RequestStatus.denied : "approved" in value ? RequestStatus.approved : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorshipLeaderRequest>): Array<WorshipLeaderRequest> {
    return value.map((x)=>from_candid_WorshipLeaderRequest_n14(_uploadFile, _downloadFile, x));
}
function to_candid_ActiveSession_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActiveSession): _ActiveSession {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    transposeSteps: bigint;
    chordMode: string;
    activeSetlistId?: SetlistId;
    lastUpdated: bigint;
    activeSongId?: SongId;
    capoFret: bigint;
}): {
    transposeSteps: bigint;
    chordMode: string;
    activeSetlistId: [] | [_SetlistId];
    lastUpdated: bigint;
    activeSongId: [] | [_SongId];
    capoFret: bigint;
} {
    return {
        transposeSteps: value.transposeSteps,
        chordMode: value.chordMode,
        activeSetlistId: value.activeSetlistId ? candid_some(value.activeSetlistId) : candid_none(),
        lastUpdated: value.lastUpdated,
        activeSongId: value.activeSongId ? candid_some(value.activeSongId) : candid_none(),
        capoFret: value.capoFret
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
